version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build: .
    command: docker/bin/start-rails
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp

volumes:
  postgres:
  maildir: